export const FETCH_ALL_DECKS = "FETCH_ALL_DECKS";
export const UPDATE_PRIORITY_SCORE = "UPDATE_PRIORITY_SCORE";
export const UPDATE_DECK_REDUX = "UPDATE_DECK_REDUX";
export const CREATE_NEW_DECK = "CREATE_NEW_DECK";
export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
